name: Deploy ThreeNodes

on:
  push:
    branches:
      - master # 代码提交的时候触发构建部署
  schedule:
    - cron: "0 14 * * *"  # 定时任务：每天下午14点钟触发
  
env:
  TZ: Asia/Shanghai
  

jobs:
  build: # 一项叫做build的任务

    runs-on: ubuntu-latest # 在最新版的Ubuntu系统下运行
    
    steps:
    - name: Checkout # 将仓库内master分支的内容下载到工作目录
      uses: actions/checkout@v1 # 脚本来自 https://github.com/actions/checkout
      
    - name: Use Node.js 8.x # 配置Node环境
      uses: actions/setup-node@v1 # 配置脚本来自 https://github.com/actions/setup-node
      with:
        node-version: "8.x"
        
    - name: install module
      run: |
        npm install compass
        npm install -g grunt-cli
        npm install -d
        grunt build
        ls -l 
        
    
    
    
      
